### PR TITLE
Visual Studio 2017 support

### PR DESCRIPTION
**Pull request by SNiLD**
I've made changes so that the library compiles with Visual Studio 2017 on Windows. Older versions of Visual Studio that support c++11 probably work as well.

I've also added export macros so that the library can be used as dynamic library (which is the way I need it).

`COVERAGE` build type and `WARNING_HELL` are not supported on Windows. Also I haven't created Windows version of the clang `check-format` script. However I tried to keep the format and style consistent with the way the library was developed.

### CODE REVIEW

**Comment by mariokonrad** [comment]
A rather large patch. I'd like to review it. Please grant me some time.

**Comment by mariokonrad** [comment]
Thank you for your work. I have some comments:

1. I like the commit 665c7a5, the double comparisons are definitely better.

2. 359c617 has too many pragmas for my taste. For this use case, I understand they are probably needed (TBH, I haven't had contact with VC++ in a long time). However, the pragmas and enclosing ifdef/endif preprocessor commands are sprinkled all over the place, which is exact opposite of what I try to do: avoid pragmas, reduce preprocessor stuff as much as possible.

3. The request for supporting MSVC came up in the past. I'm afraid, my interest in Windows as supported platform is little to none. Further, I have no infrastructure to test MSVC builds, nor the time to set one up. I have considered appveyor, but had too little time to look into it.

I'll think about it, but I heavily lean towards cherry-picking 665c7a5 and leave the rest for now.

**Comment by SNiLD** [comment]
The pragmas can be avoided if the interface doesn't expose any STL stuff (i.e. no member variables that are STL types, member functions and return types are fine as STL types).

**Comment by mariokonrad** [comment]
This is a restriction I don't want to commit to. Quite the contrary. Instead of rolling my own `utils::optional`, I'd love to use `std::optional`, but this is C++17 and I don't want to exclude C++11 right now.

**Comment by SNiLD** [comment]
I understand that you don't want Windows as a platform that you provide "official" support for. Maybe you still could add this to the library and list it as "might work, but unsupported".

It's also unfortunate that MSVC whines about C4251. However disabling it for the whole project and getting rid of the preprocessor ifdefs would lead to real problems to be not reported.

If you end up not accepting Windows support for the project at all could you at least consider the changes from https://github.com/mariokonrad/marnav/pull/12/commits/16474f047ee1c1ae2a9635d35e58ba478a724ad8 that are not made to the `CMakeLists.txt` so that the support burden for keeping the forks in sync would be minimal? What I specifically mean is:
 * Rename reserved words `TRUE`, `RELATIVE` and `pascal` to `TRUE_NORTH`, `RELATIVE_NORTH` and `Pa` respectively
 * Don't use keyword `or` but instead use `||`.
 * Don't construct objects and directly use assignment operators on them (like `*=`, `+=`, `-=`) in `matrix2`, `matrix3`, `matrix4`, `matrix_n`, `quaternion`, `vector2`, `vector3`, `vector4`, `vector_n`.
   * Some of these changes also use the more optimal route of directly constructing the objects to proper parameters.
 * Use `size_type` `int` for `vector` classes because accessing them is usually done like `vector2[0]`, instead of `vector2[0u]`.
 * Missing `<array>` and `<algorithm>` includes from some headers

**Comment by mariokonrad** [comment]
I really want to thank you for your work, and I do not wish to sound ungrateful, but...

I'm terribly sorry, you probably won't like this.

> I understand that you don't want Windows as a platform that you provide "official" support for. Maybe you still could add this to the library and list it as "might work, but unsupported".

No. I don't want to clutter the code with a lot of unsupported stuff, especially preprocessor. Same goes for `CMakeLists.txt` files.

> Rename reserved words `TRUE`, `RELATIVE` and `pascal` to `TRUE_NORTH`, `RELATIVE_NORTH` and `Pa` respectively

None of those are keywords in the C++ standard.

`Pa` instead of `pascal` would break consistency with the other pressure unit `bar`, nor is it consistent naming (PascalCase vs. snake_case). I'm aware that this is part of the MSVC compiler. Standard conformity can be configured using `/Za` option (see https://msdn.microsoft.com/en-us/library/0k0w269d.aspx).

I have nothing special against MSVC, I just try to adhere to the standard as far as possible without clutter in the code. The top level `CMakeLists.txt` also shuts down GCCs extensions (here: https://github.com/mariokonrad/marnav/blob/master/CMakeLists.txt#L18-L20). Maybe there is even an issue in CMake if it doesn't do this for MSVC.

> Don't use keyword `or` but instead use `||`.

Frankly, `or` *is* a keyword.

> Don't construct objects and directly use assignment operators on them (like `*=`, `+=`, `-=`) in `matrix2`, `matrix3`, `matrix4`, `matrix_n`, `quaternion`, `vector2`, `vector3`, `vector4`, `vector_n`. 

Most changes in the PR in this regard are more elaborate, spread over three lines instead of one. To be honest I like the terse one, if not related to:

> Some of these changes also use the more optimal route of directly constructing the objects to proper parameters.

You're right. Good point.

> Use `size_type int` for vector classes because accessing them is usually done like `vector2[0]`, instead of `vector2[0u]`.

Yes you're right. But: std containers also have an unsigned integer for `size_type`, this is for consistency reasons, although it's clear to me that `vector2` is not a container in the same sense as `std::vector` or `std::array`, but consistency is nice nonetheless.

> Missing `<array>`, `<algorithm>` and `<tuple>` includes from some headers

You're right.

> Also changes from 126e29b are relevant (they're only warnings though).

Yes, part of this is related to 665c7a5.

So, again, I want to thank you for your effort. I will merge some of it, in one way or another, of course with proper attribution. But I'm afraid, MSVC support is not part of it.

**Comment by SNiLD** [comment]
> None of those are keywords in the C++ standard.

That is true, but they are defined in [minwindef.h](https://github.com/tpn/winsdk-10/blob/master/Include/10.0.10240.0/shared/minwindef.h) and [WinGDI.h](https://github.com/ldarren/tge-152-fork/blob/master/lib/MSPlatformSDK/Include/WinGDI.h) which are automatically included every time you try to develop anything on Windows.

> Pa instead of pascal would break consistency with the other pressure unit bar, nor is it consistent naming (PascalCase vs. snake_case).

The name of the unit could be anything that is not reserved word. Naming of Pa is exactly consistent with the pressure unit bar (see how SI units are named). Naming is not consistent with other enums in that file either because of the UPPERCASE naming in `reference` instead of the same snake_case as in other enums so which one is it and why isn't `reference` in snake_case? (because **true** in lower case is reserved word even in C++ standard!). [Enumerators should not use all caps](https://github.com/isocpp/CppCoreGuidelines/blob/master/CppCoreGuidelines.md#Renum-caps).

It would be better if all the enums/variables exposed by this library would be named so that they do not cause conflicts with reserved words even if those words are reserved in other systems (as long as we know about them) so that the API could be kept the same even though you don't officially support other platforms.

>  I'm aware that this is part of the MSVC compiler. Standard conformity can be configured using /Za option (see https://msdn.microsoft.com/en-us/library/0k0w269d.aspx).

**Restricting library whose public API exposes features that do not compile with extensions enabled restricts the whole projects that try to use that library to compile their code with extensions disabled as well.**

> Frankly, or is a keyword.

Yes like I said don't use `or` keyword but use `||` instead. `or` is alternative token for the primary token `||` which is provided so that systems and keyboards that do not have `|` can still use this code. GCC always keeps `or` keyword available but MSVC only makes it available if you include `iso646.h` or compile with `/Za` (the reason why this is bad is provided in previous paragraph).

> Most changes in the PR in this regard are more elaborate, spread over three lines instead of one. To be honest I like the terse one

I like the shorter ones as well but MSVC tries to compile the classes as `const` so that the `*=` etc operators do not actually work and in case of `normalize(value_type len = 1.0) const` method they actually lead to infinite recursion!

**Comment by mariokonrad** [comment]
A bunch of insightful information, but not much new, I'm afraid.

> **Restricting library wh...**

No need to go bold here, thank you.

> ... but they are defined in `minwindef.h` and `WinGDI.h` ...

True, but TBH, this of no interest to me.

> MSVC tries to compile the classes as `const`

Didn't know that.

To quote from above: 
>  I will merge some of it, in one way or another, of course with proper attribution. But I'm afraid, MSVC support is not part of it.

**Comment by mariokonrad** [comment]
So, I have merged some stuff, leave out the rest. It's time to close the issue.

**Pull request closed without merging**
